version: '3.4'

services:
  blockshop.api:
    image: ${DOCKER_REGISTRY-}blockshop.api
    container_name: blockshop.api
    build:
      context: .
      dockerfile: src/BlockShop.Api/Dockerfile
    ports:
      - "25625:25625"
      - "25626:25626"
    environment:
      - ASPNETCORE_HTTP_PORTS=25625
      - ASPNETCORE_HTTPS_PORTS=
    volumes:
      - ./.containers/db:/db
  blockshop.web:
    image: ${DOCKER_REGISTRY-}blockshop.web
    container_name: blockshop.web
    depends_on: 
      - blockshop.api
    build:
      context: .
      dockerfile: src/BlockShop.Web/Dockerfile
    ports:
      - "25627:25627"
      - "25628:25628"
    environment:
      - ASPNETCORE_HTTP_PORTS=25627
      - ASPNETCORE_HTTPS_PORTS=
